[package]
name = "example-ws-chat-with-salvo-websocket"
version.workspace = true
edition.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util.workspace = true
once_cell.workspace = true
salvo-websocket .workspace = true
tokio = { workspace = true, features = ["macros"] }
salvo = { workspace = true, features = ["ws"] }
serde = { workspace = true, features = ["derive"] }
tokio-stream = { workspace = true, features = ["net"] }
tracing .workspace = true
tracing-subscriber .workspace = true
