[workspace]
members = ["crates/*", "examples/*"]

[workspace.package]
version = "0.37.1"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
description = """
Salvo is a powerful and simplest web server framework in Rust world.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["http", "async", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]

[workspace.dependencies]
aead = "0.5"
aes-gcm = "0.10"
anyhow = "1"
async-compression = "0.3"
async-session = "3"
async-trait = "0.1"
base64 = "0.13"
bytes = "1"
bcrypt = "0.13"
cookie = "0.16"
chacha20poly1305 = "0.10"
cruet = "0.13"
encoding_rs = "0.8"
enumflags2 = "0.7"
etag = "3"
fastrand = "1"
form_urlencoded = "1"
futures-util = "0.3"
headers = "0.3"
http = "0.2"
hmac = "0.12"
hex = "0.4"
hyper = "0.14"
hyper-rustls = "0.23"
jsonwebtoken = "8"
mime = "0.3"
mime_guess = "2"
moka = "0.9"
multer = "2"
multimap = "0.8"
once_cell = "1"
openssl = "0.10"
path-slash = "0.2"
parking_lot = "0.12"
percent-encoding = "2"
pin-project = "1"
rand = "0.8"
rcgen = "0.10"
regex = "1"
ring = "0.16"
reqwest = "0.11"
rustls-pemfile = "1.0"
rust-embed = "6"
salvo_macros = { version = "0.37.1", path = "./crates/macros" }
salvo_core = { version = "0.37.1", path = "./crates/core" }
salvo_extra = { version = "0.37.1", path = "./crates/extra" }
salvo-cache = { version = "0.37.1", path = "./crates/cache" }
salvo-cors = { version = "0.37.1", path = "./crates/cors" }
salvo-csrf = { version = "0.37.1", path = "./crates/csrf" }
salvo-flash = { version = "0.37.1", path = "./crates/flash" }
salvo-rate-limiter = { version = "0.37.1", path = "./crates/rate-limiter" }
salvo-session = { version = "0.37.1", path = "./crates/session" }
salvo-static = { version = "0.37.1", path = "./crates/static" }
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
sha2 = "0.10"
syn = "1"
tempfile = "3"
textnonce = "1"
thiserror = "1"
time = "0.3"
tokio = "1"
tokio-native-tls = "0.3"
tokio-rustls = "0.23"
tokio-openssl = "0.6"
tokio-stream = "0.1"
tokio-util = "0.7"
tokio-tungstenite = "0.17"
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
darling = "0.14"
proc-macro-crate = "1"
proc-macro2 = "1"
quote = "1"
x509-parser = "0.14"
