[package]
name = "example-unix-socket"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../crates/salvo" }
salvo-static = { path = "../../crates/static" }
tokio = { version = "1", features = ["macros"] }
