[package]
name = "example-catch-error"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1"
eyre = "0.6"
salvo = { path = "../../crates/salvo", features = ["anyhow", "eyre"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
