[package]
name = "example-template-askama"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
askama = "0.11"
salvo = { path = "../../crates/salvo" }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
