[package]
name = "example-oapi-todos"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
once_cell = "1"
salvo = { workspace = true, features = ["affix", "size-limiter", "oapi"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1"
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true