[package]
name = "example-compression"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../crates/salvo", features = ["compression"] }
salvo-static = { path = "../../crates/static" }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
