[package]
name = "example-work-with-tower"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
hyper = { version = "0.14", features = ["server"] }
salvo = { path = "../../crates/salvo" }
tokio = { version = "1", features = ["macros"] }
tower = { version = "0.4", features = ["limit"] }
tracing = "0.1"
tracing-subscriber = "0.3"
