[package]
name = "example-db-mongodb"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
salvo = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
once_cell = "1"
futures.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
mongodb = "2"
thiserror = "1"
