[package]
name = "example-hello-h3"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { path = "../../crates/salvo", features = ["http3"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1"
futures = "0.3"
quinn = { version = "0.8", default-features = false, features = ["tls-rustls", "ring"] }
# rcgen = { version = "0.9" }
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.1"
