[package]
name = "salvo_core"
version.workspace = true
authors = ["Chrislearn Young <chrislearn@hotmail.com>", "driftluo <driftluo@foxmail.com>"]
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
license.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["cookie", "http1", "fix-http1-request-uri", "http2", "test"]
full = ["cookie", "http1", "fix-http1-request-uri", "http2", "quinn", "rustls", "native-tls", "openssl", "unix", "test", "anyhow"]
cookie = ["dep:cookie"]
http1 = []
fix-http1-request-uri = ["http1"]
http2 = []
quinn = ["dep:salvo-http3", "dep:salvo-quinn", "dep:quinn", "rustls"]
rustls = ["dep:tokio-rustls", "dep:rustls-pemfile"]
native-tls = ["dep:tokio-native-tls", "dep:native-tls"]
openssl = ["dep:openssl", "dep:tokio-openssl"]
unix = []
test = ["dep:async-compression", "dep:base64", "dep:encoding_rs", "dep:serde_urlencoded", "dep:url", "tokio/macros"]
# acme = ["dep:base64", "hyper/client", "dep:hyper-rustls", "dep:rcgen", "dep:ring", "dep:x509-parser", "dep:tokio-rustls", "dep:rustls-pemfile"]

[dependencies]
cruet.workspace = true
anyhow = { workspace = true, optional = true }
async-compression = { workspace = true, features = ["brotli", "deflate", "gzip", "tokio"], optional = true }
async-trait.workspace = true
base64 = { workspace = true, optional = true }
http-body-util.workspace = true
bytes.workspace = true
cookie = { workspace = true, features = ["percent-encode"], optional = true }
encoding_rs = { workspace = true, optional = true }
enumflags2.workspace = true
fastrand.workspace = true
form_urlencoded.workspace = true
futures-util = { workspace = true, default-features = false, features = ["io"] }
headers.workspace = true
http.workspace = true
hyper = { workspace = true, features = ["server", "http1", "http2", "client"] }
# hyper-util = { workspace = true, features = ["runtime", "http1", "http2", "tcp"] }
hyper-rustls = { workspace = true, optional = true }
mime.workspace = true
mime_guess.workspace = true
multer.workspace = true
multimap = { workspace = true, features = ["serde"] }
once_cell.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
pin-project = { workspace = true }
quinn = { workspace = true, optional = true, features = ["tls-rustls", "ring"] }
quinn-proto = { workspace = true, optional = true }
rcgen = { workspace = true, optional = true }
regex.workspace = true
ring = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
salvo-http3 = { workspace = true, optional = true }
salvo_macros.workspace = true
salvo-quinn = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
serde_urlencoded = { workspace = true, optional = true }
tempfile.workspace = true
textnonce.workspace = true
thiserror.workspace = true
openssl = { workspace = true, optional = true }
tokio = { workspace = true, features = ["fs", "net", "rt-multi-thread"] }
tokio-native-tls = { workspace = true, optional = true }
native-tls = { workspace = true, optional = true, features = ["alpn"] }
tokio-rustls = { workspace = true, optional = true }
tokio-openssl = { workspace = true, optional = true }
tokio-stream = { workspace = true, default-features = false }
tracing.workspace = true
url = { workspace = true, optional = true }
x509-parser = { workspace = true, optional = true }
