[package]
name = "example-ws"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
futures-util.workspace = true
salvo = { workspace = true, features = ["ws"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
serde = "1"
serde_json = "1"
