[package]
name = "example-csrf-session-store"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { path = "../../crates/salvo" }
salvo-csrf = { default-features = false, features = ["session-store", "bcrypt-cipher"], path = "../../crates/csrf" }
salvo-session = { path = "../../crates/session" }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
