name: ci-linux

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: check release build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests --release

      - name: tests
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --all --all-features --no-fail-fast -- --nocapture

      - name: Generate coverage file
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/main' || github.event_name == 'push')
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --all-features -p salvo_macros salvo_core salvo_extra salvo-session salvo-flash salvo-cors salvo-csrf salvo-cache salvo-rate-limiter salvo-static --out Xml

      - name: Upload to codecov
        if: matrix.version == 'stable' && (github.ref == 'refs/heads/main' || github.event_name == 'push')
        uses: codecov/codecov-action@v3
        with:
          file: cobertura.xml

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache
