name: ci-macos

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Check ${{ matrix.version }} - x86_64-apple-darwin
    runs-on: macOS-12

    steps:
      - uses: actions/checkout@v3

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-apple-darwin
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: check build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: check release build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests --release

  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          # - nightly

    name: Test ${{ matrix.version }} - x86_64-apple-darwin
    runs-on: macOS-12
    needs: [check]
    steps:
      - uses: actions/checkout@v3

      - name: Install ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-apple-darwin
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cargo test
        uses: actions-rs/cargo@v1
        timeout-minutes: 40
        with:
          command: test
          args: --all --all-features --no-fail-fast -- --nocapture