on: push

name: rustfmt

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - uses: actions-rust-lang/rustfmt@v1