name: website

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest
    environment: website
    env:
      DOCS_GA_ID: G-X828N63WC8
      NODE_VERSION: '18'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: 'yarn'
          # cache: yarn

      - name: Install dependencies
        run: |
          cd website
          npm install -g yarn
          yarn install
          yarn run build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: salvo-rs/salvo-rs.github.io
          target_branch: main
          build_dir: website/.vuepress/dist
        env:
          GH_PAT: ${{ secrets.GH_PAGES_TOKEN }}