[package]
name = "example-websocket-chat"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
futures-util.workspace = true
once_cell = "1"
salvo = { workspace = true, features = ["websocket"] }
tokio = { workspace = true, features = ["macros"] }
tokio-stream = { workspace = true, features = ["net"] }
tracing.workspace = true
tracing-subscriber.workspace = true
